databases:
  - name: edu_planner
    databaseName: edu_planner_production_database_cybw
    user: edu_planner_production_user

services:
  - type: web
    name: eduplanner
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: edu_planner_production_database_cubw
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
